name: Continuous Integration

on: [pull_request]

jobs:
  Ubuntu-22-04-pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: ./scripts/install.sh
      - name: format python
        run: black --config pyproject.toml --check ${{ github.workspace }}/get_mp3_from_url
      - name: pylint
        run: pylint --load-plugins=pylint.extensions.docparams  ${{ github.workspace }}/get_mp3_from_url
      - name: unit-test
        run: coverage run --source=get_mp3_from_url -m unittest discover -v -b -s ${{ github.workspace }}
      - name: test-coverage
        run: coverage report -m --omit="/usr/*,/home/runner/.local/*" --fail-under=100
      - name: acceptance test
        run: ./scripts/acceptance_test.sh
